# Generated by Django 3.0.5 on 2020-08-14 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('price', models.FloatField(verbose_name='Preço')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/%Y/%m/', verbose_name='Imagem(Opcional)')),
                ('slug', models.SlugField(unique=True)),
                ('digital', models.BooleanField(default=False, null=True)),
                ('tipo', models.CharField(choices=[('V', 'Variável'), ('S', 'Simples')], default='V', max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('price', models.FloatField(verbose_name='Preço')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='Estoque')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
            ],
            options={
                'verbose_name': 'Variação',
                'verbose_name_plural': 'Variações',
            },
        ),
    ]
