# Generated by Django 3.0.5 on 2020-08-26 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Complement',
            new_name='complement',
        ),
    ]
