# Generated by Django 3.0.5 on 2020-08-31 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200826_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qtd_total',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
